export const ACTION_TYPES = {
  MOCK_REPORT: {
    LOAD_MOCK_REPORT: "LOAD_MOCK_REPORT",
    GET_MOCK_REPORT: "GET_MOCK_REPORT",
    SAVE_MOCK_REPORT: "SAVE_MOCK_REPORT",
  },
  INSTRUCTION_REPORT: {
    LOAD_INSTRUCTION_REPORT: "LOAD_INSTRUCTION_REPORT",
    GET_INSTRUCTION_REPORT: "GET_INSTRUCTION_REPORT",
    SAVE_INSTRUCTION_REPORT: "SAVE_INSTRUCTION_REPORT",
    FILTER_INSTRUCTION_REPORT: "FILTER_INSTRUCTION_REPORT",
    PAGINATE_INSTRUCTION_REPORT: "PAGINATE_INSTRUCTION_REPORT",
  },
};
